export interface DiskInfo {
  id: string;
  name: string;
  mountPoint: string;
  totalBytes: number;
  availableBytes: number;
  isRemovable: boolean;
  fileSystem: string;
}

export interface Endpoint {
  id: string;
  diskId: string | null;
  label: string;
  path: string;
  /** True while `label` was generated by Auto Label and not since manually edited. */
  isAutoLabel: boolean;
}

export type AddEndpointPathResult =
  | { ok: true; added: boolean; endpoint: Endpoint }
  | { ok: false; added: false; error: string };
