export interface DiskInfo {
  id: string;
  name: string;
  mountPoint: string;
  totalBytes: number;
  availableBytes: number;
  isRemovable: boolean;
  fileSystem: string;
}

export interface Endpoint {
  diskId: string;
  label: string;
  path: string;
  /** True while `label` was generated by Auto Label and not since manually edited. */
  isAutoLabel: boolean;
}
