/** Curated re-export of the `lucide-react` icons actually used in the app --
 * every call site imports from here instead of `lucide-react` directly, so
 * the icon set stays a single reviewable list. Default size/stroke width in
 * each usage should stay close to `JobActionIcons`' hand-drawn set (~14-16px,
 * strokeWidth 1.75) so the two icon sources read as one visual language. */
export {
  Settings,
  HardDrive,
  ArrowLeftRight,
  X,
  Plus,
  Trash2,
  FolderOpen,
  FolderInput,
  FolderOutput,
  EyeOff,
  Tag,
  Pencil,
  ArrowRightLeft,
  ShieldCheck,
  ExternalLink,
  ArrowUpFromLine,
  Inbox,
  TriangleAlert,
  FolderTree,
  Eye,
  Save,
  RefreshCw,
  ChevronDown,
  ChevronUp,
  Video,
  Music,
  Image as ImageIcon,
  File,
  FileText,
  History,
} from "lucide-react";
